name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # roda a cada 12 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout para ler o repositório
      - uses: actions/checkout@v3

      # Gerar a animação da cobra
      - uses: Platane/snk@v3
        with:
          github_user_name: GabrielCoelhoeSilva
          outputs: |
            dist/github-contribution-grid-snake.svg

      # Publicar no branch "output"
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
